name: Unit test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install coverage
    - name: Add dependencies about external libraries
      run: |
        pip install h5py
        pip install fastapi
        pip install websockets
        pip install httpx
        pip install numpy
        pip install git+https://github.com/m-labs/sipyco.git
        pip install git+https://github.com/m-labs/artiq.git
    - name: Run the unit tests and check coverage
      run: |
        xvfb-run `which coverage` run -m unittest test.py
        xvfb-run `which coverage` report main.py
